eqlabs/zksync-state-reconstruct

src/lib.rs, src/state.rs
This PR implements `TryFrom` trait for `CommitBlockInfoV1` and encapsulates the Eth token parsing into corresponding type.
=> Encapsulate field parsing

Cargo.toml, src/main.rs
This is first step towards CLI command of state reconstruction tool.
=> Introduce CLI command

.gitignore, Cargo.toml, src/lib.rs, src/state.rs, src/tree.rs
- Introduces a RocksDB-backed Merkle Tree:
- Populates the genesis state from a CSV-file on creation.
- Support for inserting a given `CommitBlockInfoV1` and returning the new L2 block number.
- Fixes some minor `clippy` complaints.
**For now the database is purged before each run since we need to figure out a way to also persist the index to key mappings.**
=> Introduce RocksDB-backed Merkle Tree

src/l1_fetcher.rs, src/main.rs
After further discussion & experimentation, it turns out that `Arc` was indeed unnecessary.
So let's get rid of it for now :stuck_out_tongue:
=> Drop unnecessary use of Arc wrapping

.rustfmt.toml, Cargo.toml, src/cli.rs, src/l1_fetcher.rs, src/main.rs, src/processor/tree/mod.rs, src/processor/tree/tree_wrapper.rs, src/types.rs
- Move CLI-arguments to `cli.rs`.
- Use derive-style `clap` instead of builder.
- Introduce common `.rustfmt.toml` settings.
=> Use derive-style `clap`

Cargo.toml, src/cli.rs, src/constants.rs, src/main.rs, src/processor/tree/mod.rs, src/processor/tree/snapshot.rs, src/processor/tree/tree_wrapper.rs
- A new CLI-argument for choosing the path to the database directory.
- Accompanying environment variable for overriding the path: `ZK_SYNC_DB_PATH`.
=> feat: db path argument

Cargo.toml, src/cli.rs, src/main.rs, src/processor/json/mod.rs, src/processor/mod.rs, src/types.rs
This change adds hidden `download` command that can be used to download L2 state from L1 and save it into JSON file in pre-processed format.
The JSON serialization format is first iteration and not optimized yet.
=> Add support to download from L1 to JSON file

src/processor/tree/mod.rs
_Writes the state snapshot on each block received instead of when the receiver is empty._
- Fixes an issue where the state file would never get written.
=> ref: save state on each block received

src/types.rs
In present state, the smart contract bytecode in L1 batches is not compressed, so remove decompression as it obviously fails.
=> Don't decompress L1 bytecode (it isn't)

src/cli.rs
Originally `download` command was only meant for development testing, but it seems to be useful for other means as well, so this change will reveal it publicly in `help` print.
=> Reveal `download` command

Cargo.lock, Cargo.toml, src/l1_fetcher.rs, src/processor/tree/mod.rs
Implements graceful shutdown by intercepting the `CTRL-C` signal and shutting down the tasks once they've finished, in order.
=> feat: ctrl-c handling

src/l1_fetcher.rs, src/processor/tree/tree_wrapper.rs
Prints total progress and number of processed blocks:
=> Add some metrics for L1 processing

src/l1_fetcher.rs
Fixes an issue where the application, at start, would send unnecessary requests equal to the `BLOCK_STEP` value.
=> ref: update latest l1 block on exit only

src/main.rs, src/processor/tree/query_tree.rs
New output:
```fish
Batch: 12
Root Hash: d1fe897f75c4c90e9555028df17556dc0afd9e9d4369899a8ae9a50178773dab
```
With `--json`:
```fish
{"batch":12,"root_hash":"d1fe897f75c4c90e9555028df17556dc0afd9e9d4369899a8ae9a50178773dab"}
```
=> ref: include batch number in root hash query

src/l1_fetcher.rs
- Splits the extremely long `L1Fetcher::run` method by moving the main task handles into separate `spawn` methods.
- Some tweaks to the metrics to allow them to be printed out as soon as possible instead of waiting until all the values have been saturated.
=> ref: split run function

Cargo.lock, Cargo.toml, src/cli.rs, src/main.rs, src/processor/mod.rs, src/processor/snapshot/mod.rs, src/processor/snapshot/types.rs
Implements a skeleton of the export snapshot functionality.
Currently only handles the partial exporting of storage logs. Storage logs processing are missing handling of `enumeration_index` & `L1Metadata` that needs to be procured through the fetcher.
=> feat: initial export snapshot skeleton

Cargo.lock, Cargo.toml, src/processor/snapshot/bytecode.rs, src/processor/snapshot/mod.rs
Factory deps (smart contracts in zkSync) are stored separately in snapshots, but they must be gathered together with storage log entries when fetching the state from L1. This change will do preliminary work required for writing out the separate factory dep snapshot file.
=> Hash & gather factory deps to snapshot

.github/workflows/ci.yml
The clippy check wasn't failing on warnings, this PR fixes that along with adjusting the test check.
=> ci: adjust checks

Cargo.lock, Cargo.toml, src/main.rs, src/processor/snapshot/database.rs, src/processor/snapshot/mod.rs, src/processor/snapshot/types.rs, src/processor/tree/mod.rs, src/processor/tree/query_tree.rs, src/processor/tree/tree_wrapper.rs
Snapshot export requires that storage log compaction takes place over the whole history of L2. Therefore we must download all commit blocks from L1 to intermediate DB before we can export the snapshot chunks.
=> Add intermediate DB for gathering snapshot data

README.md, flake.nix
- Clarify that we only support using the Nix flake on Linux systems
- Closes #55
=> doc: clarify flake availability

state-reconstruct-fetcher/src/l1_fetcher.rs
Occasionally, the program doesn't end cleanly when interrupted. This is a fix for an especially common error:
```
thread 'tokio-runtime-worker' panicked at state-reconstruct-fetcher/src/l1_fetcher.rs:259:61:
called `Result::unwrap()` on an `Err` value: SendError { .. }
```
The error in this case being "channel closed", as the receiver apparently shut down first.
=> ignoring send error during shutdown

.gitignore, src/main.rs, state-reconstruct-fetcher/src/l1_fetcher.rs, state-reconstruct-fetcher/src/metrics.rs
- Instead of incrementing `*_blocks_processed` calculate the number of blocks by comparing the current block number with the block number the tool was started on. This also fixes an issue that was present earlier, where the number of blocks processed was inflated and not accurately represented on first launch.
- The percentage calculation is now based on total progress from the genesis block (or `start_block` if that's been supplied) instead of total progress from the last stored block.
=> tweak: adjust how metrics are collected

Cargo.lock, Cargo.toml, src/main.rs, src/processor/snapshot/mod.rs, src/processor/snapshot/types.rs, src/processor/tree/tree_wrapper.rs, state-reconstruct-fetcher/Cargo.toml, state-reconstruct-fetcher/src/constants.rs, state-reconstruct-fetcher/src/l1_fetcher.rs, state-reconstruct-fetcher/src/metrics.rs, state-reconstruct-fetcher/src/types/mod.rs, state-reconstruct-fetcher/src/types/v1.rs, state-reconstruct-fetcher/src/types/v2.rs
- Implements reconstruction of state using Boojum-formatted blocks
=> feat: reconstructing state using `CommitBlockInfoV2`

Cargo.lock, Cargo.toml, src/cli.rs, src/main.rs, src/processor/snapshot/database.rs, src/processor/snapshot/exporter.rs, src/processor/snapshot/importer.rs, src/processor/snapshot/mod.rs, src/processor/tree/mod.rs, src/processor/tree/tree_wrapper.rs, state-reconstruct-fetcher/src/l1_fetcher.rs
- Adds `--snapshot` flag to the reconstruct command that allows importing latest state from a snapshot.
=> feat: snapshot imports

src/processor/snapshot/exporter.rs, src/processor/snapshot/importer.rs, src/processor/snapshot/mod.rs, src/processor/snapshot/types.rs, src/processor/tree/tree_wrapper.rs
Introduces a new trait, `Proto`, that defines methods for converting between native structs and ones generated by protobuf, and ones for encoding/decoding those structs into/from gzipped protobuf files.
Notably, `SnapshotStorageLogsChunk` and `SnapshotFactoryDependencies` leverage these methods to simplify the snapshot export/import code further and avoid intermingling structs from `protobuf::*` with `types::*`.
=> ref: abstract away protobuf from snapshot

.gitignore, README.md
- Adds a new table of contents section.
- Adds a section detailing usage of snapshot utilities.
- Tweaks:
- Update output code blocks to match the current output of the commands.
- Adds `--release` flag to all the commands.
- Fix some `markdownlint` lints.
=> doc: update readme

Cargo.lock, Cargo.toml, src/processor/snapshot/importer.rs, src/processor/tree/tree_wrapper.rs
* Enables importing snapshot without reliance on a header file. If a snapshot header file is not found within the specified snapshot folder, the importer will instead try to generate one using the filenames of the other contents as a base.
* Adjusts the importing process to extend the tree each chunk instead of after all have been collected. This alleviates an issues wherein trying to recover from large snapshots could trigger warning signals to the shell and be sent `SIGKILL` forcefully as a result.
=> feat: import snapshots without header file present

state-reconstruct-fetcher/src/constants.rs
The previous value of `128` uses up a lot of RPC-calls for very little actual benefit, and in some cases it even makes the tool run slower when ran with unreliable RPC-providers.
=> tweak: higher `BLOCK_STEP`

Dockerfile
- Adds missing dependencies.
- Installs Rust via `rustup` (so we can use the version specified in `.rust-toolchain.toml`).
=> docker: update dockerfile

src/cli.rs, src/main.rs, src/processor/snapshot/exporter.rs, src/processor/snapshot/importer.rs, src/processor/snapshot/mod.rs, src/processor/tree/tree_wrapper.rs, state-reconstruct-fetcher/src/l1_fetcher.rs, state-reconstruct-fetcher/src/metrics.rs, state-reconstruct-storage/src/snapshot.rs, state-reconstruct-storage/src/types.rs
- Adds a mapping function to L1 fetcher that takes in any L1 batch number and tries to find its corresponding L1 block number by using binary search on fetched logs.
- Removes `num_chunks` argument. We now use the default chunk size of `1_000_000` to calculate how many chunks we need instead.
- Fixes some smaller miscellaneous issues with the snapshots
=> feat: map l1 batch numbers to their l1 block number equivalent
